app = "brtai"

[build]
  dockerfile = "Dockerfile"

[env]
  APP_ENV = "production"
  APP_DEBUG = "false"

[[services]]
  internal_port = 8080
  processes = ["app"]
  
  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80
  
  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443