/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "boost.browser-logs": [],
    "sanctum.csrf-cookie": [],
    "google.redirect": [],
    "google.callback": [],
    "events.public.show": [
        {
            "name": "event",
            "required": true,
            "binding": "slug"
        }
    ],
    "events.public.participate": [
        {
            "name": "event",
            "required": true,
            "binding": "slug"
        }
    ],
    "dashboard": [],
    "dashboard.analytics": [],
    "events.index": [],
    "events.create": [],
    "events.store": [],
    "events.show": [
        {
            "name": "event",
            "required": true,
            "binding": "id"
        }
    ],
    "events.edit": [
        {
            "name": "event",
            "required": true,
            "binding": "id"
        }
    ],
    "events.update": [
        {
            "name": "event",
            "required": true,
            "binding": "id"
        }
    ],
    "events.destroy": [
        {
            "name": "event",
            "required": true,
            "binding": "id"
        }
    ],
    "events.publish": [
        {
            "name": "event",
            "required": true,
            "binding": "id"
        }
    ],
    "events.unpublish": [
        {
            "name": "event",
            "required": true,
            "binding": "id"
        }
    ],
    "events.analytics": [
        {
            "name": "event",
            "required": true,
            "binding": "id"
        }
    ],
    "price-tiers.store": [
        {
            "name": "event",
            "required": true,
            "binding": "id"
        }
    ],
    "price-tiers.update": [
        {
            "name": "priceTier",
            "required": true,
            "binding": "id"
        }
    ],
    "price-tiers.destroy": [
        {
            "name": "priceTier",
            "required": true,
            "binding": "id"
        }
    ],
    "price-tiers.toggle": [
        {
            "name": "priceTier",
            "required": true,
            "binding": "id"
        }
    ],
    "events.participants": [
        {
            "name": "event",
            "required": true,
            "binding": "id"
        }
    ],
    "participants.update": [
        {
            "name": "participant",
            "required": true,
            "binding": "id"
        }
    ],
    "participants.destroy": [
        {
            "name": "participant",
            "required": true,
            "binding": "id"
        }
    ],
    "participants.check-in": [
        {
            "name": "participant",
            "required": true,
            "binding": "id"
        }
    ],
    "events.export.participants": [
        {
            "name": "event",
            "required": true,
            "binding": "id"
        }
    ],
    "events.export.financials": [
        {
            "name": "event",
            "required": true,
            "binding": "id"
        }
    ],
    "payment.checkout": [
        {
            "name": "participant",
            "required": true
        }
    ],
    "payment.success": [
        {
            "name": "participant",
            "required": true
        }
    ],
    "payment.status": [
        {
            "name": "participant",
            "required": true
        }
    ],
    "ai.suggestions": [],
    "ai.generate": [],
    "ai.suggestions.apply": [
        {
            "name": "suggestion",
            "required": true,
            "binding": "id"
        }
    ],
    "ai.suggestions.feedback": [
        {
            "name": "suggestion",
            "required": true,
            "binding": "id"
        }
    ],
    "suppliers.index": [],
    "suppliers.show": [
        {
            "name": "supplier",
            "required": true,
            "binding": "id"
        }
    ],
    "suppliers.byCategory": [
        {
            "name": "category",
            "required": true
        }
    ],
    "suppliers.suggest": [],
    "settings.index": [],
    "settings.profile.update": [],
    "settings.billing": [],
    "settings.upgrade-pro": [],
    "settings.upgrade-success": [],
    "settings.check-upgrade-status": [
        {
            "name": "transactionId",
            "required": true
        }
    ],
    "profile.edit": [],
    "profile.update": [],
    "profile.destroy": [],
    "register": [],
    "login": [],
    "password.request": [],
    "password.email": [],
    "password.reset": [
        {
            "name": "token",
            "required": true
        }
    ],
    "password.store": [],
    "verification.notice": [],
    "verification.verify": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "hash",
            "required": true
        }
    ],
    "verification.send": [],
    "password.confirm": [],
    "password.update": [],
    "logout": [],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
